pkg_origin=
pkg_name=mytutorialapp
pkg_version=0.2.0
pkg_maintainer="The Habitat Maintainers <humans@habitat.sh>"
pkg_license=()
pkg_upstream_url=https://github.com/scarolan/habitat-example-plans
pkg_source=nosuchfile.tar.gz
pkg_deps=()
pkg_expose=()
